[project]
name = 'Headphone-Tangling-Quantum-Mechanics-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.cable-knot-complexity-exponential-growth-engine]
path = 'contracts/cable-knot-complexity-exponential-growth-engine.clar'
clarity_version = 3
epoch = '3.2'

[contracts.untangling-frustration-amplification-algorithm]
path = 'contracts/untangling-frustration-amplification-algorithm.clar'
clarity_version = 3
epoch = '3.2'

[contracts.wireless-headphone-battery-death-nostalgia-inducer]
path = 'contracts/wireless-headphone-battery-death-nostalgia-inducer.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
